Fix style issues
Gunivers/Gipsy pull request #116
Opened 2023-02-12 16:46 UTC by Aeris1One

Cette PR a pour but de fixer enfin les 300+ erreurs que nous balance PyLint à chaque PR.
On vas le faire petit à petit, mais on vas le faire !

J'ai commencé par le plugin Quizz parce que c'était de loin le plus moche.

N'hésitez pas à push sur cette branche, la seule règle c'est de faire un commit par plugin ou par élément du coeur pour garder un historique propre. Je conseille d'utiliser PyCharm et l'extension PyLint (qui nécessite d'installer PyLint dans le venv via `pip install pylint` et d'aller valider la valeur par défaut dans les paramètres de PyCharm -> Autres -> PyLint)

2023-02-12 17:47 UTC, Leirof requested changes
Erreur au lancement du bot

<details>
<summary>Logs</summary>

```
ENVIRONMENT: uname_result(system='Windows', node='Vince-HeavyTower', release='10', version='10.0.22623', machine='AMD64')

12/02/2023 at 18:47:03 | [INFO] ▶️ Starting Gipsy...
12/02/2023 at 18:47:07 | [INFO] [32m✅ Bot connected
12/02/2023 at 18:47:07 | [INFO] Nom : Gipsy Dev
12/02/2023 at 18:47:07 | [INFO] ID : 786546781919641600
12/02/2023 at 18:47:07 | [INFO] Connected on 2 servers:
 - Gipsy Sandbox
 - T E S T
12/02/2023 at 18:47:07 | [ERROR] Failed to load extension: plugins.quizz.quizz
12/02/2023 at 18:47:07 | Full traceback below.

Traceback (most recent call last):
  File "C:\Users\vince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\bot.py", line 934, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\plugins\quizz\quizz.py", line 18, in <module>
    from quipyquizz import QuiPyQuizz
ModuleNotFoundError: No module named 'quipyquizz'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\vince\Documents\Dev\Gunivers\Gipsy\start.py", line 93, in load
    await bot_client.load_extension(extension)
  File "C:\Users\vince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\bot.py", line 1012, in load_extension
    await self._load_from_module_spec(spec, name)
  File "C:\Users\vince\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\ext\commands\bot.py", line 937, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'plugins.quizz.quizz' raised an error: ModuleNotFoundError: No module named 'quipyquizz'

12/02/2023 at 18:47:07 | [INFO] 28 plugins loaded, 1 plugins failed
```

</details>

2023-02-12 18:06 UTC, Leirof reviewed
Yep, it work ^^

2023-02-12 18:06 UTC, ascpial approved these changes
je ne vois rien qui peut casser ici

2023-02-12 18:07 UTC, Leirof approved these changes
LGTM

2023-02-12 18:16 UTC, Aeris1One commented on utils.py
> +        Pour toute autre requête, retourne l'ID de la ligne affectée si returnrowscount,
Ce commentaire ne veut strictement rien dire, je suspecte Copilot d'y être pour quelque-chose...

2023-02-12 18:23 UTC, ascpial commented on utils.py
> +        Pour toute autre requête, retourne l'ID de la ligne affectée si returnrowscount,
Ça ne veut pas rien dire, mais ça peut être plus clair

2023-02-12 19:02 UTC, Aeris1One commented on utils.py
> +        Pour toute autre requête, retourne l'ID de la ligne affectée si returnrowscount,
C'est surtout que le commentaire dit deux fois "si returnrowscount" pour deux évènements opposés

2023-02-23 08:47 UTC, ascpial reviewed
Il faut noter que je retire de temps en temps des `try: ... except:` globaux qui n'affichent pas l'erreur.

Je préfère que on ai des messages d'erreurs que l'ont puisse résoudre plutôt que de ne jamais savoir que quelque chose ne fonctionne pas.

2023-02-23 08:47 UTC, ascpial reviewed
Il faut noter que je retire de temps en temps des `try: ... except:` globaux qui n'affichent pas l'erreur.

Je préfère que on ai des messages d'erreurs que l'ont puisse résoudre plutôt que de ne jamais savoir que quelque chose ne fonctionne pas.

2023-02-25 10:20 UTC, Leirof approved these changes
LGTM mais y'a beucoup de petits changements donc avoir 1 ou 2 avis en plus serait intéressant

2023-02-25 10:34 UTC, Aeris1One commented on bot/utils/configManager.py
>      def __init__(self, manager, serverID, value):
Pourquoi l'argument `serverID` ne doit pas passer en snake_case ?

2023-02-25 13:02 UTC, fantomitechno reviewed
J'ai relu tout (c'était long) et à part les quelques remarques, je ne vois rien posant grandement problème. 
Je n'ai pas pu tester le bon fonctionnement du bot cependant.

NB : il y a à un endroit deux lettres qui sont échangés dans une docstring (je l'ai perdu de vu et j'ai pas pensé à le notifier)

2023-02-25 13:04 UTC, ascpial commented on plugins/admin/admin.py
>  sys.path.append("./bot")
Bien vu, il va falloir la supprimer

2023-02-25 13:04 UTC, ascpial commented on utils.py
> +        :return: La configuration du serveur
Il va falloir discuter de la docstring, ce n'est pas le focus principal de cette PR pour le moment.

2023-02-25 13:19 UTC, ascpial commented on bot/utils/configManager.py
>      def __init__(self, manager, serverID, value):
C'est passé sous le radar

2023-02-25 13:20 UTC, ascpial commented on utils.py
> +        Pour toute autre requête, retourne l'ID de la ligne affectée si returnrowscount,
Résolu dans le dernier commit au moment de l'écriture.
Dans la traduction correct, le premier "si returnrowscount" est invalide, l'id de la ligne affecté est retourné par défaut.

2023-03-17 09:23 UTC, ascpial commented
Tu peux résoudre les conflits ?

2023-03-22 19:55 UTC, Aeris1One commented
LGTM si le CI est content (plus que 3 ! ON PEUT LE FAIRE !)

2023-03-22 19:56 UTC, Aeris1One commented
Note : cette PR est à squash avec comme nom de commit `:art: style: fix linter warnings`

2023-03-22 20:05 UTC, ascpial commented
Je conseilles une relecture du code pour vérifier qu'il n'y a pas de conflits entre des noms de variables.

2023-03-22 20:17 UTC, ascpial commented on core/config.py
>      Called once in the main setup script."""
On refera la docstring dans une autre PR.

2023-03-22 20:58 UTC, ascpial approved these changes
Core review, fichiers vérifiés individuellements et bot testé, il se lance correctement.

2023-03-22 20:59 UTC, ascpial commented on plugins/quizz/quizz.py
>      return answer
Très bonne question, ça sera à voir sur une autre au moment de retravailler ce plugin en particulier.

2023-03-25 10:16 UTC, Leirof approved these changes

2023-03-25 10:16 UTC, merged