⏳  Show when the bot is loading
Gunivers/Gipsy pull request #118
Opened 2023-02-12 17:18 UTC by ascpial

Avec cette PR, le bot se lance en mode ne pas déranger et retourne sur le statut en ligne une fois toutes les extensions chargées.

De cette manière, il y a un indicateur visuel du côté de Discord qui indique quand est-ce que le bot peut être utilisé.

2023-02-12 17:43 UTC, Leirof requested changes
Si une commande est lancée durant la période de chargement, cela provoque une erreur

![image](https://user-images.githubusercontent.com/12165342/218327515-fc9e6da8-6726-436e-bc30-bb1f0628ac35.png)

2023-02-12 17:45 UTC, ascpial commented
C'est normal, c'était déjà le cas avant.

Le but n'est pas de résoudre ce genre de problème mais d'indiquer à partir de quand ils n'arriveront plus :wink:

2023-02-14 19:17 UTC, ZRunner commented
Modifier le statut du bot (avec change_presence) dans l'événement `on_ready` est fermement déconseillé par discord.py, notamment parce qu'il est courant que l'API Discord gère mal ce changement et déconnecte purement et simplement le bot. En plus des commentaires à ce sujet sur leur Discord, il y a un mini warning dans leur FAQ à ce sujet : https://discordpy.readthedocs.io/en/stable/faq.html#how-do-i-set-the-playing-status.

Cela étant dit, je l'utilise avec Axobot depuis des années et je n'ai jamais eu de problème particulier. Just so you know

2023-02-14 19:38 UTC, Aeris1One commented
Au vu de ce que viens de dire Z, je pense qu'il faudrait éviter de changer la présence dans `on_ready`. 
Il ne devrait pas y avoir de problème dans l'immédiat sur notre serveur, mais pour un bot hébergé sur une mauvaise connection, `on_ready` peut effectivement être appelé plusieurs fois. Idem quand nous devrons diviser le bot en shard.

2023-02-14 21:16 UTC, ascpial commented
Cet event n'est appelé qu'une fois normalement, de la même manière que le chargement des plugins.

De plus, il y a un délai lié au temps de chargement des plugins, je ne penses pas qu'il devrait y avoir de problèmes...

2023-02-14 22:07 UTC, Aeris1One commented
> Cet event n'est appelé qu'une fois normalement

Justement non, d'aprés la doc de dpy il peut être appelé plusieurs fois, et il est même indiqué qu'il faut justement eviter de croire qu'il n'est appelé qu'une fois et qu'il faut gérer les appels multiples

2023-02-15 06:47 UTC, ascpial commented
Ce que je voulais dire c'est que le chargement des plugins et le changement de statut n'est appelé qu'une fois, je suis allé un peu vite.

2023-02-15 20:24 UTC, fantomitechno commented
Le chargement des plugins et le status sont appelé dans `on_ready` sans vérification de si ils ont été déja run donc pour moi, ils ne sont pas appelé une seul fois (en prenant en compte le fait que le `on_ready` puissent être appelé plusieurs fois comme l'a dit @Aeris1One )

Il faudrait donc soit une vérification que c'est bien la première fois que le bot se lance (ou l'unique fois, selon la volonté derrière)

2023-02-15 20:32 UTC, ascpial commented
Voilà, maintenant quand le bot charge, le listener est retiré, ce qui a pour effet de ne charger les plugins et de changer le statut qu'une seule fois dans la vie du bot.

2023-02-18 09:18 UTC, Leirof approved these changes
LGTM, mais j'aimerais quand même avoir l'avis de @ZRunner là dessus

2023-02-18 16:52 UTC, ZRunner approved these changes
LGTM

2023-02-18 17:04 UTC, merged