Doc refactor
Gunivers/Gipsy pull request #119
Opened 2023-02-13 10:33 UTC by Leirof

Prévisualisation dispo ici : https://gipsy.readthedocs.io/en/doc_refactor/

2023-02-14 19:22 UTC, ZRunner commented
Il y a pas mal de fautes d'anglais, notamment dans le readme. DeepL a sorti un correcteur de texte vachement sympa si tu veux pas te prendre la tête, ça peut aider : https://www.deepl.com/write

J'ai aussi remarqué un petit nombre d'incohérences dans la doc des commandes, notamment sur le format des commandes (parfois avec un slash, parfois sans ; parfois dans du markdown `, parfois pas, etc.). Le but de cette PR est-il aussi d'uniformiser un minimum ces documentations ?

2023-02-19 17:45 UTC, ascpial approved these changes
Je suis allé voir la preview sur readthedocs, LGTM

2023-02-19 19:46 UTC, ascpial requested changes
Après une vérification plus en détail, il ne devrait pas y avoir "Did I help you" à la suite de chaque plugin sur la page d’accueil.

2023-02-19 20:22 UTC, ascpial commented
Peut-être qu'il serait possible d'ajouter l'information pour contribuer automatiquement, de la même manière que la partie pour laisser un commentaire ?

2023-02-19 20:29 UTC, ascpial commented
S'il était possible aussi de régler cette petite ligne manquante :

![image](https://user-images.githubusercontent.com/72463129/219973578-af3332cc-91d0-41f4-b605-b760b68b1f45.png)

2023-02-19 20:45 UTC, ascpial commented
Je ne préfère pas toucher à la ligne manquante avant la mise à jour du thème qui risque de tout casser.

2023-02-20 08:23 UTC, merged