📉 Tweak(XP) xp reduction
Gunivers/Gipsy pull request #61
Opened 2022-10-13 15:48 UTC by LeiRoF

@ZRunner need help 😅 

J'ai deux truc que j'arrive pas à faire marcher et j'avoue que je commence à saturer là mdr, peut être que tu peux m'aider vu que c'est toi qui a designé ce plugin ^^

2022-10-13 16:43 UTC, ZRunner reviewed
xp.py ligne 68 : c'est pas un peu dangereux de mettre l'argument par défaut à `False` ? Autant ne pas mettre de valeur par défaut non ?

2022-10-13 16:44 UTC, ZRunner requested changes
xp.py ligne 155 : y a une ligne vide pour rien, et un code commenté un peu plus bas, ça me stresse

2022-10-13 16:46 UTC, ZRunner requested changes
xp.py ligne 285 : ce typage n'est valide qu'à partir de python 3.10. Il faut soit modifier les prérequis du bot pour python 3.10 à la place de 3.9 actuellement, soit utiliser `typing.Union`

2022-10-13 16:47 UTC, ZRunner requested changes
xp.py ligne 287 : y a une très belle fonction `isinstance()` pour éviter de comparer deux types, qui fonctionne bien mieux vu qu'elle gère aussi les les classes héritées etc. :)

2022-10-13 16:48 UTC, ZRunner requested changes
xp.py ligne 413 : à vue de nez, si l'utilisateur n'est pas dans la bdd (ie. n'a jamais gagné d'xp), ça crash avec un IndexError

2022-10-14 18:19 UTC, ZRunner approved these changes

2022-10-14 18:30 UTC, theogiraudet approved these changes

2022-10-14 18:44 UTC, merged