📄 Docs: added changelog and migration guides
Gunivers/Gipsy pull request #70
Opened 2022-11-01 07:39 UTC by LeiRoF

2022-11-01 17:26 UTC, ZRunner commented on docs/DEV_MIGRATION_GUIDE.md
> +This function return a doctionary containing the config information such as defined in the `/plugins/foo/config.yaml` file. This file must contains the default config for the plugin and will never be
Typo sur dictionary :)

2022-11-01 17:27 UTC, ZRunner commented on docs/USER_MIGRATION_GUIDE.md
> +# User migration guid
Manque un e à guide

2022-11-01 17:45 UTC, ZRunner approved these changes

2022-11-01 17:49 UTC, Aeris1One approved these changes
LGTM

2022-11-01 17:52 UTC, ascpial requested changes

2022-11-01 17:52 UTC, ascpial commented on docs/USER_MIGRATION_GUIDE.md
> +Then, replace all the files with the new ones.
Peut-être que cette ligne pourrait être plus précise : "Remplacez les anciens fichiers et plugins par ceux mis à jour" ou qqch du genre

2022-11-01 17:53 UTC, LeiRoF commented on docs/USER_MIGRATION_GUIDE.md
> +Then, replace all the files with the new ones.
Pas convaincu

2022-11-01 17:55 UTC, ascpial commented on docs/USER_MIGRATION_GUIDE.md
> +Then, replace all the files with the new ones.
Je trouve que c'est un peu vague dans sa forme actuelle

2022-11-01 17:57 UTC, LeiRoF commented on docs/USER_MIGRATION_GUIDE.md
> +Then, replace all the files with the new ones.
D'autres avis ?

2022-11-02 12:22 UTC, ascpial approved these changes

2022-11-02 12:24 UTC, merged