📂feat: amélioration de la structure de fichiers
Gunivers/Gipsy pull request #71
Opened 2022-11-02 13:15 UTC by ascpial

Cette PR fait suite à la modification du système de configuration et termine la modification de la structure des fichiers.

Les fichiers liés au code du bot sont maintenant tous dans le dossier `/core/`, qui est maintenant un module python, ce qui permet par exemple de faire `from core import Gunibot` plutôt que de devoir importer depuis le fichier où la classe est déclarée.

L'ordre imports a été refait de manière consistante dans tous les fichiers en suivant la logique suivante : en premier les module built-in, un saut de ligne, les module installés via pip (discord.py, LRFutils...), un saut de ligne et enfin l'importation des modules locaux (core par exemple).

Autre modification, pour des soucis de consistance avec les autres plugins, la fonction `setup` du plugin rss a été déplacée en bas du fichier.

2022-11-02 20:10 UTC, ZRunner commented on core/utils/errors.py
> +from core import config
Pourquoi ne pas mettre les 5 imports `from core` sur la même ligne ?

2022-11-02 20:10 UTC, ZRunner commented on core/utils/sconfig.py
> -from utils import CONFIG_OPTIONS, Gunibot, MyContext
Autant en profiter pour supprimer les fonctions commentées en fin de fichier (lignes 320-358) et créer un ticker pour les refaire au propre plus tard imo

2022-11-02 20:10 UTC, ZRunner commented on plugins/misc/misc.py
> +from typing import Union
`except ValueError` (ligne 149), profitons-en ça coûte rien :)

2022-11-02 20:14 UTC, ascpial commented on core/utils/errors.py
> +from core import config
Très bonne question, je change ça tout de suite (probablement parce que j'ai remplacé bot et utils sans réfléchire...)

2022-11-02 20:22 UTC, ZRunner approved these changes
LGTM

2022-11-04 06:31 UTC, LeiRoF commented
> Autre modification, pour des soucis de consistance avec les autres plugins, la fonction setup du plugin rss a été déplacée en bas du fichier.

C'est du détail, mais je l'avais mise en haut car plus facile d'accès, et je pense qu'il faudrait faire de même pour les autres plugins (de la même façon que la fonction __init__ se trouve toujours en haut d'une classe, ça me parait plus logique d'avoir cette fonction setup au début, proche justement de la fonction __init__ qu'elle appelle

2022-11-04 06:37 UTC, LeiRoF requested changes
Les plugins ayant été déplacé sur le répo dédié, leur modification engendrera des conflits en plus de devoir être bougé ensuite.

La meilleure solution serait alors de supprimer les plugin à l'instar de ce qui a été fait sur la branche beta) et de reporter ces changements sur une PR sur le répo des plugins

2022-11-04 06:46 UTC, LeiRoF commented
Pour ce qui est de bouger les fichiers dans `/core/`, ne serait-il pas mieux de le faire progressivement au fur et à mesure de la réécriture de ces dit fichier ?

Leur position est secondaire, c'est leur réécriture qui est particulièrement importante, et j'avais l'idée de ne bouger dans `/core/` que ce qui a été réécrit de sorte à voir ce qui est fait ou pas

2022-11-04 08:53 UTC, ascpial commented
> Les plugins ayant été déplacé sur le répo dédié, leur modification engendrera des conflits en plus de devoir être bougé ensuite.
> 
> La meilleure solution serait alors de supprimer les plugin à l'instar de ce qui a été fait sur la branche beta) et de reporter ces changements sur une PR sur le répo des plugins

Dans l'état actuel, comme on peut le voir sur le bouton "merge pull request" de github, il n'y a pas de conflits puisque la branche visée est la branche rewrite, sur laquelle les modifications n'ont pas été faite.
Je penses donc que l'on peut merge cette PR et déplacer les plugins ensuite, pour plus de simplicité.

2022-11-04 08:54 UTC, ascpial commented
> Pour ce qui est de bouger les fichiers dans `/core/`, ne serait-il pas mieux de le faire progressivement au fur et à mesure de la réécriture de ces dit fichier ?
> 
> Leur position est secondaire, c'est leur réécriture qui est particulièrement importante, et j'avais l'idée de ne bouger dans `/core/` que ce qui a été réécrit de sorte à voir ce qui est fait ou pas

L’avantage de déplacer et de modifier les fichiers d'un coup est qu'il y aura moins de conflits compliqués à régler entre différentes PR si elle modifient le même fichier (par exemple si deux PRs déplacent le même fichier, mais font des modifications différentes après, ça peut être compliqué à régler).

2022-11-04 10:44 UTC, LeiRoF approved these changes
Je suis pas convaincu que ce soit les meilleurs choix, mais je comprends tes arguments et je ne vois aucun soucis sur la PR alors si @theogiraudet valide, LGTM

2022-11-11 10:02 UTC, Aeris1One approved these changes
LGTM

2023-02-12 11:49 UTC, merged