Readd plugins
Gunivers/Gipsy pull request #94
Opened 2023-02-11 18:13 UTC by ascpial

Cette PR ajoute de nouveau les plugins dans ce repo, comme @Leirof l'a demandé.

L'historique de ce qui a été modifié depuis que les plugins ont été retirés a été conservé, de cette manière tout est conservé tel quel.

Cette branche est à tester avant de merge.

2023-02-11 18:21 UTC, ascpial reviewed
J'ai testé rapidement, le bot se lance et les plugins semblent fonctionner

2023-02-11 18:31 UTC, Aeris1One commented on plugins/.github/workflows/deploy_gipsy-beta.yaml
> +name: Deploy Gipsy Beta
Hum, pourquoi les workflows semblent avoir étés modifiés ?

2023-02-11 18:35 UTC, ascpial commented on plugins/.github/workflows/deploy_gipsy-beta.yaml
> +name: Deploy Gipsy Beta
Aucune idée 🤔

2023-02-11 20:15 UTC, Leirof requested changes
Il faudrait retirer :
- .github/*
- .gitignore
- README.md

2023-02-11 20:57 UTC, ascpial commented
J'ai aussi retiré `plugins/` du `.gitignore`.
Ça peut servir.

2023-02-11 22:01 UTC, Leirof approved these changes
LGTM

2023-02-12 08:39 UTC, ascpial commented on plugins/.github/workflows/deploy_gipsy-beta.yaml
> +name: Deploy Gipsy Beta
C'est les workflow qu'il y avait dans l'autre repo, ils n'ont pas été modifiés.
Je les ai supprimés.

2023-02-12 08:39 UTC, merged